import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Free AI Flashcard Maker.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-foreground mb-8">Terms of Service</h1>
        <div className="prose prose-sm max-w-none text-muted leading-relaxed space-y-6">
          <p><strong>Effective Date:</strong> April 2026</p>
          <p>By using flashcardmaker.app, you agree to these Terms of Service.</p>
          <h2 className="text-xl font-semibold text-foreground mt-8">1. Service Description</h2>
          <p>Free AI Flashcard Maker is a web-based tool that uses AI to generate study flashcards. The service is free and does not require registration.</p>
          <h2 className="text-xl font-semibold text-foreground mt-8">2. Acceptable Use</h2>
          <p>Use the service only for lawful, educational purposes. Do not attempt to overload, reverse-engineer, or abuse the service.</p>
          <h2 className="text-xl font-semibold text-foreground mt-8">3. AI-Generated Content</h2>
          <p>Flashcards are generated by AI and may occasionally contain inaccuracies. Always verify important information with authoritative sources. Generated flashcards are for personal study use.</p>
          <h2 className="text-xl font-semibold text-foreground mt-8">4. Limitation of Liability</h2>
          <p>The service is provided &quot;as is&quot; without warranties. We are not liable for any damages from using or relying on AI-generated flashcard content.</p>
          <h2 className="text-xl font-semibold text-foreground mt-8">5. Contact</h2>
          <p>Questions? Contact us at <a href="mailto:legal@flashcardmaker.app" className="text-primary hover:underline">legal@flashcardmaker.app</a>.</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
